### ISSUE TITLE
Url not valid

### ISSUE THREAD

**Issue by alkampfergit** [atymic/sitemap-ping-action#2]
I've simply added your action to my pipeline, but I got *Sitemap URL is not valid* error.

This is how I added the action, what am I doing wrong?

```
#      - name: 'Ping search engines'
#        uses: atymic/sitemap-ping-action@master
#        with:
#          sitemapUrl: 'http://www.codewrecks.com/sitemap.xml'
```

**Comment by atymic** [comment]
Oops, think the docs might be wrong:
https://github.com/atymic/sitemap-ping-action/blob/master/src/index.ts#L6

Should be:

```
#      - name: 'Ping search engines'
#        uses: atymic/sitemap-ping-action@master
#        with:
#          sitemap-url: 'http://www.codewrecks.com/sitemap.xml'
```

Will update the docs! Thanks for the issue.

**Comment by atymic** [comment]
Fixed in https://github.com/atymic/sitemap-ping-action/commit/5b857215d0b89ab16a90ac0be870249d958da8a9

Thanks!
